#!/usr/bin/env python
if __name__ == "__main__":
    import sys
    import pyrit_cli
    try:
        pyrit_cli.Pyrit_CLI().initFromArgv()
    except (KeyboardInterrupt, SystemExit):
        sys.stderr.write("Interrupted...\n")
    except pyrit_cli.PyritRuntimeError as e:
        sys.exit(e)
